### ISSUE TITLE
IconButton: ツールチップが見切れないように下左右にも表示できるようにしたい

### ISSUE THREAD

**Issue by knokmki612** [tuqulore/jumpu-ui#176]
現状ツールチップをつける場合上向きにしかつけられず、ページ上部に配置するとツールチップが見切れることがある

見切れないよう配置によって下左右にもツールチップを表示できるようにしたい

下向きにする場合以下のようなスタイルでの上書きが必要

```css
.icon-button [role='tooltip'] {
  transform: translateX(-50%) translateY(150%) scale(0);
}
.icon-button:hover [role='tooltip'] {
  transform: translateX(-50%) translateY(150%) scale(1);
}
```

このようなスタイルをコンポーネントのスタイルとして管理しようとするとmodifier的なクラスが必要になりそうだがそれは避けたい

ツールチップの配置を変更する手段を提供するもしくは変更方法をドキュメンテーションできたら完了
